import { Option } from './type';

export const INTEREST_OPTIONS: Option[] = [
  { id: 1, title: 'Comedy', selected: false },
  { id: 2, title: 'Daily Life', selected: false },
  { id: 3, title: 'Entertainment Culture', selected: false },
  { id: 4, title: 'Outdoors', selected: false },
  { id: 5, title: 'Travel', selected: false },
  { id: 6, title: 'Oddly Satisfying', selected: false },
  { id: 7, title: 'Food & Drink', selected: false },
  { id: 8, title: 'Auto & Vehicle', selected: false },
  { id: 9, title: 'Animals', selected: false },
  { id: 10, title: 'Gaming', selected: false },
  { id: 11, title: 'Sports', selected: false },
  { id: 12, title: 'Family', selected: false },
  { id: 13, title: 'Beauty & Style', selected: false },
  { id: 14, title: 'DIY', selected: false },
  { id: 15, title: 'Anime & Comics', selected: false },
  { id: 16, title: 'Music', selected: false },
  { id: 17, title: 'Science & Education', selected: false },
  { id: 18, title: 'Fitness & Health', selected: false },
  { id: 19, title: 'Home & Garden', selected: false },
  { id: 20, title: 'Art', selected: false },
  { id: 21, title: 'Motivation & Advice', selected: false },
  { id: 22, title: 'Life Hacks', selected: false },
  { id: 23, title: 'Dance', selected: false },
];
